R/global_r_plugin.vim

I think at some point the execution command arguments changed from needing to be provided as strings to a list of strings.
Also, I have a question on the topic of using the plugin as a global plugin.  When using, say, python, I obviously, don't need nvimcom to load.  A while ago, we could skip this waiting by using an option like `let vimrplugin_vimcom_wait = -1`.  That is, something negative.  This doesn't seem to be supported any longer.  Any particular reason?  Could we re-implement it?  Or do you want to try to do something smarter; for example if `R_exe` is set, don't call the `WaitVimComStart()` function?

Update global args to be lists rather than strings

---

R/common_global.vim
doc/Nvim-R.txt

Useful for global plugin where nvimcom is never to be loaded, hence
there is no reason to wait for it to load.

Suggest nvimcom_wait -1 to skip waiting.

---

R/common_global.vim

Note that the lines above looking for double dots (e.g. line 1132)
let lines = map(copy(lines), 'substitute(v:val, "^\\.\\. \\?", "", "")')
are left unchanged, simply because I do not know yet what the double
dots would represent in markdown. But a similar issue might occure there
is someone had a variable name starting with a dot (not common style,
but allowed in R).

Fixes #14 regular expression to identify triple back-ticks too greedy

---

R/nvimbuffer.vim

On nvim, I run R in an nvim buffer.  Sometimes, I hide or put the R buffer onto another tab and still send lines of code.  However, if the R buffer is hidden or on another tab and a line of code is sent and setwidth is on, then a new split is created for the R buffer.  This change prevents the creation of a new split for the R buffer by not doing setwidth if the R buffer is not on the current tab.
I thought a better way would be to eschew the ExeOnRTerm call (which I believe is the source of the problem) and just run something like
```
let s:rwnwdth = windwidth(get_win_nr_function(g:rplugin_R_bufname))
```
But I can't seem to find a `get_win_nr_function()`

Don't jump to R buffer if not on tab

---

R/common_global.vim

When using neovim with true color by setting `$NVIM_TUI_ENABLE_TRUE_COLOR=1`, `has("gui_running")` reports 1 which breaks the heuristic to determine if a tmux split is possible.

fix heuristic to detect if a tmux split is possible

---

R/nvimbuffer.vim

The ExeOnRTerm function jumps to the term buffer running R and then back to the previous buffer.  However, if one has the same buffer open in multiple windows, ExeOnRTerm jumps back to the first window that contains that buffer.  It makes more sense to jump to the window that the user was previously in rather than just the first window that contains the buffer.
This simple patch should switch the user back to the previous window.   I also don't think that we need to worry about the switchbuf variable anymore, but please correct me if I am wrong.

Jump to previous window not previous buffer

---

R/common_global.vim

Fixes issue preventing zathura version check from failing when warning messages are printed, e.g.:
```
$ zathura --version            
** (zathura:9061): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-fDiIqj367q: Connection refused
zathura 0.3.5
(plugin) pdf-poppler (0.2.6) (/usr/lib/zathura/pdf.so)
```

Ignoring dbus, etc. warning messages when checking Zathura version

---

R/common_global.vim

The `NAME=VALUE` syntax to set the nvimcom port before opening a PDF does not work for the fish shell. I've replaced it with a call to `env NAME=VALUE` which should also work on other shells (I've tried sh, bash and zsh).

Use env to set temporary environment variables (fixes opening PDFs using fish shell)

---

R/rstudio.vim

Addressing #142.  This starts RStudio on Linux (i.e. `has("win32")` is false).  The nvim version works for me.  I don't have vim to test the vim version.

Adapt StartRStudio() for linux

---

R/common_global.vim
doc/Nvim-R.txt

When using `:RInsert` to insert the output of a long (i.e. time-consuming) command, I always got the "No reply" warning and the output wouldn't be inserted, even if the command ran perfectly.  So, I decided to make the "waiting time" variable and added an option for it (which probably could have a better name). I also wrote an entry on the `doc`.

Add R_wait_reply option

---

R/common_global.vim

A user can be using another R program such as `rice` and `rplugin_Rcmd` defaults to `R_app` which should be `rice` is that case.

use rplugin_Rcmd instead of rplugin_R

---

R/common_global.vim
doc/Nvim-R.txt

`let g:R_bracketed_paste = 1` to enable bracket paste mode so that `\l` will send the whole block to [rice](https://github.com/randy3k/rice) with bracketed paste mode.

enable brackted paste mode

---

R/nvimcom/R/nvim.interlace.R

I ran into trouble where the PDF file could not be found after `rmarkdown::render()` because a chunk has changed the working directory. I think it should be generally safe to use the absolute path as returned by `render()` to find the PDF file (correct me if I'm wrong), so I removed the regex that removed the path.

Use absolute path as returned by rmarkdown::render to open pdf

---

R/common_global.vim

Selecting a python executable with `executable()` might not work if there is an executable binary present that returns an error, as when using pyenv. This workaround uses exit code rather than executability to select a python to use. Fixes #278.

Choose python executable by exit code (fixes #278)

---

R/common_global.vim
R/nvimcom/R/specialfuns.R

Before, if anything went wrong with completion, this `while` loop would go on forever, effectively crashing vim. This forces the loop to end after some time, so the completion fails but the whole vim process doesn't die.
See #288 for discussion.
This PR is a superset of #292. I'm submitting it separately because it might be a more controversial fix than #288, and may warrant further discussion and/or a more elegant solution.

Escape from infinite completion loop

---

R/common_global.vim

Especially when writing packages, I like to be explicit about where functions are coming from. Often, I don't load the entire packages when doing so to avoid polluting the global namespace.
This PR makes it so that `:call Raction("help")` will recognize the full `pacakge::object` form, even if the package is not loaded.
So far, this seems to work fine for function calls with and without `::`, so I don't _think_ this should break anything. But perhaps you had a good reason for the old behavior that I wasn't aware of?

Allow Rhelp to register package::function

---

R/nvimcom/R/nvim.help.R

If pkgload::dev_help can't find dev docs, fall back to utils::help.
This should fix #314, which occurs when help is called on a function of an attached package that wasn't loaded by devtools or pkgload.  For example, any base function.

Fall back to installed docs (fixes #314)

---

R/nvimcom/R/nvim.help.R

The help is broken on my system, and #317 did not fix it. AFAICT the logic in https://github.com/jalvesaq/Nvim-R/blob/master/R/nvimcom/R/nvim.help.R#L42-L64 is flawed. E.g., if `devtools` is not loaded (https://github.com/jalvesaq/Nvim-R/blob/master/R/nvimcom/R/nvim.help.R#L54), nevertheless call a function of devtools in https://github.com/jalvesaq/Nvim-R/blob/master/R/nvimcom/R/nvim.help.R#L55.
I re-wrote and tested this block with both `devtools` and `pkgload`, and it seems to work on my box.

Fix help for devtools / pkgload

---

R/extern_term.vim
R/tmux.vim

Some users load their custom tmux.conf with the R_notmuxconf = 1 option
and define the "pane-base-index" to start at something other than 0.
Since SendCmdToR_Term only looks for pane 0, this causes the function to
fail. When calling the SendCmdToR_Term() function, query the pane-base-index
from tmux directly and use the value.

Query Tmux for pane-base-index

---

R/nvimcom/R/nvim.bol.R

Here we provide the same implementation as is available in later
versions of R

file.mtime does not exist in R versions <= 3.1

---

R/nvimcom/R/nvimcom.R

See https://github.com/jalvesaq/Nvim-R/issues/384
Most source functions in NVim-R call `NvimR.source()` behind the scene. Add a default `local = parent.frame()` in `NvimR.*()` will make sure the source functions work as expected in debug mode.

Add `local = parent.frame()` in NvimR.* functions

---

R/tmux.vim

Closes #400. I've tried adding a regex (i.e `master\|next`) but cannot get it work so I do a new substitution. Feel free to modify it.

Fix tmux version when tmux -V reports things like `next-3.0`

---

R/nvimcom/R/nvim.bol.R

This PR fixes a comparison where a logical vector of arbitrary length is used in a `if()`. Only pops up if the respective environment variables are set and if the locale has at least two elements, but under these circumstances the package does not build, exiting with the exception:
```
Error in !is.na(localeToCharset()) && localeToCharset()[1] == "UTF-8" : 
'length(x) = 2 > 1' in coercion to 'logical(1)'
```
Note that these additional checks might become enabled by default in future R versions.

Fix nvimcom for _R_CHECK_LENGTH_1_CONDITION_=true and _R_CHECK_LENGTH_1_LOGIC2_=true

---

R/common_global.vim

sometimes it is handy to use the motions known in vim to select a region that should be sent to R. This is now possible with the `\m` command, e.g. `\m}` (end of paragraph) or `\m3j` (the next 3 lines including current line).

Send arbitrary lines and motion region to R

---

doc/Nvim-R.txt

This is from https://github.com/jalvesaq/Nvim-R/issues/173#issuecomment-288066282
I'm using the kitty terminal emulator and IME, it's necessary to set both lines to achieve this effect.

update console width documentation

---

R/bibcompl.vim

I was having trouble getting \od to open the files listed in my .bib, so
I dug into the source code and find the error. There was a [0] where
there should have been a fls[0].
As always, thanks for the amazing plugin. I hope I've done my very small
part to contribute.

fixed a very small error that caused me a huge headache

---

R/common_global.vim

Reset `s:user_data` to {}, after exiting completion menu, so that new completions will not contain previous data.
Refer #548

clear s:user_data after (omni)completion.

---

R/extern_term.vim

This allows the R repl to run inside Alacritty if `let R_external_term = 'alacritty'` is in .vimrc (or .config/nvim/init.vim). Additionally, the tmux config that enables regular scrolling is included.

Support Alacritty as external terminal

---

R/extern_term.vim
R/tmux_split.vim

Neovim recently changed how "ctrl input pairs" like `<C-M>` etc. work (see https://github.com/neovim/neovim/pull/17825), and (as far as I understand) they are no longer equivalent to `<CR>` etc. This seems to have broken sending code from nvim to an external terminal. Replacing both instances of `<C-M>` with `<CR>` in the command line sent to the terminal (via tmux) appears to fix it, but I haven't tested this on older nvim or vim versions or with tmux splits.

Fix sending R code to terminal in newer nvim

---

R/nvimcom/R/nvimcom.R
R/start_r.vim

- Fixes #662
The default encoding for R on Windows is `"native.enc"` (Hopefully this will [change for R 4.2](https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/)). This causes an error from Nvim-R when sourcing the `start_options.R` file encoded with UTF-8 from a working directory that contains multibyte characters.
This PR adds a simple logic to fix this issue:
1. If current Vim encoding is `utf-8`, which means `writefile()` will also save files with `utf-8` encoding, write the start options in a file named `start_options_utf8.R`.
2. Otherwise, write the start options in a file named `start_options.R`, i.e. the original one.
3. When loading nvimcom, detect `start_options_utf8.R`. If it exists, source it with `encoding = "UTF-8"` option. Otherwise, …

Fix encoding issue for start options file on Windows

---

R/start_ncs.vim

On widows in the search for multiple copies of nvim-r spaces in the filename like the common `C:\Documents and Settings\...` etc., are getting split into two paths, triggering the warning that there are multiple nvim-r installs. This fixes that issue by explicitly only splitting paths on linebreaks.

Ensure only linebreak is used to split

---

R/start_r.vim
doc/Nvim-R.txt

With R_debug_center set to 1, the QuickFixLine will stay in the center
of the buffer while debugging. This provides more code context around
the line being debugged.
Let me know if the News needs changing, since I'm not sure when the versioning is incremented.
Thanks!

Add new R_debug_center option to center the QuickFixLine

---

ftplugin/quarto_nvimr.vim

Hi,
I noticed that the shortcut `\qs` which is used to stop the preview of a quarto document did not work. It seems that the `R` function `quarto::quarto_stop()` does not exist (anymore?). However, there is a function `quarto::quarto_preview_stop()` that stops the running preview. This PR just replaces the former by the latter.
Thanks for your work on this great plugin.

Edit non-existing function name

---

README.md

This should hopefully draw a little more attention to the note that Nvim-R is superseded for Neovim users.

Use callout in README

---

R/nvimcom/src/apps/nvimrserver.c
R/nvimcom/src/nvimcom.c

This fix adds nvimcom compatibility to FreeBSD. Tested on FreeBSD 14.0. Should not interfere with other os's.

Fix bsd nvimcom

---

R/common_global.vim

Creates a separate trigger for `R_assign = 2` so that it doesn't drop out of insert mode unless two underscores (or `R_assign_map` characters) are typed. Consequently, inserts like "this_variable_name" will be correctly saved to the repeat register.
However the repeat register (`@.`) is still reset if a substitution is made. This will be harder to fix.

Partial fix for  #816

---

R/gui_running.vim

at line 197 in RCreateMenuItem function call the 3rd argument is missing. I guees the correct string here is 'RQuartoStop'.

Correcting typo in R/gui_running.vim
